import React from 'react';
import { Image, Dimensions, View } from 'react-native';

const { width } = Dimensions.get('window');

const locationImages = {
    'AFGHANISTAN': require('../../assets/Location/Afghanistan.png'),
    'ALBANIA': require('../../assets/Location/Albania.png'),
    'ALGERIA': require('../../assets/Location/Algeria.png'),
    'ANDORRA': require('../../assets/Location/Andorra.png'),
    'ANGOLA': require('../../assets/Location/Angola.png'),
    'ANTIGUA & BARBUDA': require('../../assets/Location/Antigua&Barbuda.png'),
    'ARGENTINA': require('../../assets/Location/Argentina.png'),
    'ARMENIA': require('../../assets/Location/Armenia.png'),
    'AUSTRALIA': require('../../assets/Location/Australia.png'),
    'AUSTRIA': require('../../assets/Location/Austria.png'),
    'AZERBAIJAN': require('../../assets/Location/Azerbaijan.png'),
    'THE BAHAMAS': require('../../assets/Location/Bahamas.png'),
    'BAHRAIN': require('../../assets/Location/Bahrain.png'),
    'BANGLADESH': require('../../assets/Location/Bangladesh.png'),
    'BARBADOS': require('../../assets/Location/Barbados.png'),
    'BELARUS': require('../../assets/Location/Belarus.png'),
    'BELGIUM': require('../../assets/Location/Belgium.png'),
    'BELIZE': require('../../assets/Location/Belize.png'),
    'BENIN': require('../../assets/Location/Benin.png'),
    'BHUTAN': require('../../assets/Location/Bhutan.png'),
    'BOLIVIA': require('../../assets/Location/Bolivia.png'),
    'BOSNIA & HERZEGOVINA': require('../../assets/Location/Bosnia&Herzegovina.png'),
    'BOTSWANA': require('../../assets/Location/Botswana.png'),
    'BRAZIL': require('../../assets/Location/Brazil.png'),
    'BRUNEI': require('../../assets/Location/Brunei.png'),
    'BULGARIA': require('../../assets/Location/Bulgaria.png'),
    'BURKINA FASO': require('../../assets/Location/BurkinaFaso.png'),
    'BURUNDI': require('../../assets/Location/Burundi.png'),
    'CAPE VERDE': require('../../assets/Location/CapeVerde.png'),
    'CAMBODIA': require('../../assets/Location/Cambodia.png'),
    'CAMEROON': require('../../assets/Location/Cameroon.png'),
    'CANADA': require('../../assets/Location/Canada.png'),
    'CENTRAL AFRICAN REPUBLIC': require('../../assets/Location/CentralAfricanRepublic.png'),
    'CHAD': require('../../assets/Location/Chad.png'),
    'CHILE': require('../../assets/Location/Chile.png'),
    'CHINA': require('../../assets/Location/China.png'),
    'COLOMBIA': require('../../assets/Location/Colombia.png'),
    'COMOROS': require('../../assets/Location/Comoros.png'),
    'DEMOCRATIC REPUBLIC OF THE CONGO': require('../../assets/Location/DemocraticRepublicOfTheCongo.png'),
    'REPUBLIC OF THE CONGO': require('../../assets/Location/RepublicOfTheCongo.png'),
    'COSTA RICA': require('../../assets/Location/CostaRica.png'),
    "CÔTE D'IVOIRE": require('../../assets/Location/CoteDIvoire.png'),
    'CROATIA': require('../../assets/Location/Croatia.png'),
    'CUBA': require('../../assets/Location/Cuba.png'),
    'CYPRUS': require('../../assets/Location/Cyprus.png'),
    'CZECHIA': require('../../assets/Location/Czechia.png'),
    'DENMARK': require('../../assets/Location/Denmark.png'),
    'DJIBOUTI': require('../../assets/Location/Djibouti.png'),
    'DOMINICA': require('../../assets/Location/Dominica.png'),
    'DOMINICAN REPUBLIC': require('../../assets/Location/DominicanRepublic.png'),
    'ECUADOR': require('../../assets/Location/Ecuador.png'),
    'EGYPT': require('../../assets/Location/Egypt.png'),
    'EL SALVADOR': require('../../assets/Location/ElSalvador.png'),
    'EQUATORIAL GUINEA': require('../../assets/Location/EquatorialGuinea.png'),
    'ERITREA': require('../../assets/Location/Eritrea.png'),
    'ESTONIA': require('../../assets/Location/Estonia.png'),
    'ESWATINI': require('../../assets/Location/Eswatini.png'),
    'ETHIOPIA': require('../../assets/Location/Ethiopia.png'),
    'FIJI': require('../../assets/Location/Fiji.png'),
    'FINLAND': require('../../assets/Location/Finland.png'),
    'FRANCE': require('../../assets/Location/France.png'),
    'GABON': require('../../assets/Location/Gabon.png'),
    'THE GAMBIA': require('../../assets/Location/TheGambia.png'),
    'GEORGIA': require('../../assets/Location/Georgia.png'),
    'GERMANY': require('../../assets/Location/Germany.png'),
    'GHANA': require('../../assets/Location/Ghana.png'),
    'GREECE': require('../../assets/Location/Greece.png'),
    'GRENADA': require('../../assets/Location/Grenada.png'),
    'GUATEMALA': require('../../assets/Location/Guatemala.png'),
    'GUINEA': require('../../assets/Location/Guinea.png'),
    'GUINEA-BISSAU': require('../../assets/Location/Guinea-Bissau.png'),
    'GUYANA': require('../../assets/Location/Guyana.png'),
    'HAITI': require('../../assets/Location/Haiti.png'),
    'HONDURAS': require('../../assets/Location/Honduras.png'),
    'HUNGARY': require('../../assets/Location/Hungary.png'),
    'ICELAND': require('../../assets/Location/Iceland.png'),
    'INDIA': require('../../assets/Location/India.png'),
    'INDONESIA': require('../../assets/Location/Indonesia.png'),
    'IRAN': require('../../assets/Location/Iran.png'),
    'IRAQ': require('../../assets/Location/Iraq.png'),
    'IRELAND': require('../../assets/Location/Ireland.png'),
    'ISRAEL': require('../../assets/Location/Israel.png'),
    'ITALY': require('../../assets/Location/Italy.png'),
    'JAMAICA': require('../../assets/Location/Jamaica.png'),
    'JAPAN': require('../../assets/Location/Japan.png'),
    'JORDAN': require('../../assets/Location/Jordan.png'),
    'KAZAKHSTAN': require('../../assets/Location/Kazakhstan.png'),
    'KENYA': require('../../assets/Location/Kenya.png'),
    'KIRIBATI': require('../../assets/Location/Kiribati.png'),
    'KOSOVO': require('../../assets/Location/Kosovo.png'),
    'KUWAIT': require('../../assets/Location/Kuwait.png'),
    'KYRGYZSTAN': require('../../assets/Location/Kyrgyzstan.png'),
    'LAOS': require('../../assets/Location/Laos.png'),
    'LATVIA': require('../../assets/Location/Latvia.png'),
    'LEBANON': require('../../assets/Location/Lebanon.png'),
    'LESOTHO': require('../../assets/Location/Lesotho.png'),
    'LIBERIA': require('../../assets/Location/Liberia.png'),
    'LIBYA': require('../../assets/Location/Libya.png'),
    'LIECHTENSTEIN': require('../../assets/Location/Liechtenstein.png'),
    'LITHUANIA': require('../../assets/Location/Lithuania.png'),
    'LUXEMBOURG': require('../../assets/Location/Luxembourg.png'),
    'MADAGASCAR': require('../../assets/Location/Madagascar.png'),
    'MALAWI': require('../../assets/Location/Malawi.png'),
    'MALAYSIA': require('../../assets/Location/Malaysia.png'),
    'MALDIVES': require('../../assets/Location/Maldives.png'),
    'MALI': require('../../assets/Location/Mali.png'),
    'MALTA': require('../../assets/Location/Malta.png'),
    'MARSHALL ISLANDS': require('../../assets/Location/MarshallIslands.png'),
    'MAURITANIA': require('../../assets/Location/Mauritania.png'),
    'MAURITIUS': require('../../assets/Location/Mauritius.png'),
    'MEXICO': require('../../assets/Location/Mexico.png'),
    'MICRONESIA': require('../../assets/Location/Micronesia.png'),
    'MOLDOVA': require('../../assets/Location/Moldova.png'),
    'MONACO': require('../../assets/Location/Monaco.png'),
    'MONGOLIA': require('../../assets/Location/Mongolia.png'),
    'MONTENEGRO': require('../../assets/Location/Montenegro.png'),
    'MOROCCO': require('../../assets/Location/Morocco.png'),
    'MOZAMBIQUE': require('../../assets/Location/Mozambique.png'),
    'MYANMAR': require('../../assets/Location/Myanmar.png'),
    'NAMIBIA': require('../../assets/Location/Namibia.png'),
    'NAURU': require('../../assets/Location/Nauru.png'),
    'NEPAL': require('../../assets/Location/Nepal.png'),
    'NETHERLANDS': require('../../assets/Location/Netherlands.png'),
    'NEW ZEALAND': require('../../assets/Location/NewZealand.png'),
    'NICARAGUA': require('../../assets/Location/Nicaragua.png'),
    'NIGER': require('../../assets/Location/Niger.png'),
    'NIGERIA': require('../../assets/Location/Nigeria.png'),
    'NORTH KOREA': require('../../assets/Location/NorthKorea.png'),
    'NORTH MACEDONIA': require('../../assets/Location/NorthMacedonia.png'),
    'NORWAY': require('../../assets/Location/Norway.png'),
    'OMAN': require('../../assets/Location/Oman.png'),
    'PAKISTAN': require('../../assets/Location/Pakistan.png'),
    'PALAU': require('../../assets/Location/Palau.png'),
    'PALESTINE': require('../../assets/Location/Palestine.png'),
    'PANAMA': require('../../assets/Location/Panama.png'),
    'PAPUA NEW GUINEA': require('../../assets/Location/PapuaNewGuinea.png'),
    'PARAGUAY': require('../../assets/Location/Paraguay.png'),
    'PERU': require('../../assets/Location/Peru.png'),
    'PHILIPPINES': require('../../assets/Location/Philippines.png'),
    'POLAND': require('../../assets/Location/Poland.png'),
    'PORTUGAL': require('../../assets/Location/Portugal.png'),
    'QATAR': require('../../assets/Location/Qatar.png'),
    'ROMANIA': require('../../assets/Location/Romania.png'),
    'RUSSIA': require('../../assets/Location/Russia.png'),
    'RWANDA': require('../../assets/Location/Rwanda.png'),
    'SAINT KITTS & NEVIS': require('../../assets/Location/SaintKitts&Nevis.png'),
    'SAINT LUCIA': require('../../assets/Location/SaintLucia.png'),
    'SAINT VINCENT & THE GRENADINES': require('../../assets/Location/SaintVincent&TheGrenadines.png'),
    'SAMOA': require('../../assets/Location/Samoa.png'),
    'SAN MARINO': require('../../assets/Location/SanMarino.png'),
    'SÃO TOMÉ & PRÍNCIPE': require('../../assets/Location/SaoTome&Principe.png'),
    'SAUDI ARABIA': require('../../assets/Location/SaudiArabia.png'),
    'SENEGAL': require('../../assets/Location/Senegal.png'),
    'SERBIA': require('../../assets/Location/Serbia.png'),
    'SEYCHELLES': require('../../assets/Location/Seychelles.png'),
    'SIERRA LEONE': require('../../assets/Location/SierraLeone.png'),
    'SINGAPORE': require('../../assets/Location/Singapore.png'),
    'SLOVAKIA': require('../../assets/Location/Slovakia.png'),
    'SLOVENIA': require('../../assets/Location/Slovenia.png'),
    'SOLOMON ISLANDS': require('../../assets/Location/SolomonIslands.png'),
    'SOMALIA': require('../../assets/Location/Somalia.png'),
    'SOUTH AFRICA': require('../../assets/Location/SouthAfrica.png'),
    'SOUTH KOREA': require('../../assets/Location/SouthKorea.png'),
    'SOUTH SUDAN': require('../../assets/Location/SouthSudan.png'),
    'SPAIN': require('../../assets/Location/Spain.png'),
    'SRI LANKA': require('../../assets/Location/SriLanka.png'),
    'SUDAN': require('../../assets/Location/Sudan.png'),
    'SURINAME': require('../../assets/Location/Suriname.png'),
    'SWEDEN': require('../../assets/Location/Sweden.png'),
    'SWITZERLAND': require('../../assets/Location/Switzerland.png'),
    'SYRIA': require('../../assets/Location/Syria.png'),
    'TAJIKISTAN': require('../../assets/Location/Tajikistan.png'),
    'TANZANIA': require('../../assets/Location/Tanzania.png'),
    'THAILAND': require('../../assets/Location/Thailand.png'),
    'TIMOR-LESTE': require('../../assets/Location/TimorLeste.png'),
    'TOGO': require('../../assets/Location/Togo.png'),
    'TONGA': require('../../assets/Location/Tonga.png'),
    'TRINIDAD & TOBAGO': require('../../assets/Location/Trinidad&Tobago.png'),
    'TUNISIA': require('../../assets/Location/Tunisia.png'),
    'TÜRKIYE': require('../../assets/Location/Turkiye.png'),
    'TURKMENISTAN': require('../../assets/Location/Turkmenistan.png'),
    'TUVALU': require('../../assets/Location/Tuvalu.png'),
    'UGANDA': require('../../assets/Location/Uganda.png'),
    'UKRAINE': require('../../assets/Location/Ukraine.png'),
    'UNITED ARAB EMIRATES': require('../../assets/Location/UnitedArabEmirates.png'),
    'UNITED KINGDOM': require('../../assets/Location/UnitedKingdom.png'),
    'UNITED STATES OF AMERICA': require('../../assets/Location/UnitedStatesOfAmerica.png'),
    'URUGUAY': require('../../assets/Location/Uruguay.png'),
    'UZBEKISTAN': require('../../assets/Location/Uzbekistan.png'),
    'VANUATU': require('../../assets/Location/Vanuatu.png'),
    'VATICAN CITY': require('../../assets/Location/VaticanCity.png'),
    'VENEZUELA': require('../../assets/Location/Venezuela.png'),
    'VIETNAM': require('../../assets/Location/Vietnam.png'),
    'YEMEN': require('../../assets/Location/Yemen.png'),
    'ZAMBIA': require('../../assets/Location/Zambia.png'),
    'ZIMBABWE': require('../../assets/Location/Zimbabwe.png'),
  };
  

const LocationImage = ({ country }) => (
  <Image
    resizeMode="stretch"
    source={locationImages[country]}
    style={{ width: "100%", height: "100%", borderColor: 'black', borderWidth: width * 0.0025, borderRadius: width * 0.008, backgroundColor: 'white',
  
     }}
  />
);



export default LocationImage;

// width: width * 0.8, height: width * 0.8,